### ISSUE TITLE
Entity reference menu layout messed up

### ISSUE THREAD

**Issue by Blackbaud-HalleyCoplin** [blackbaud/sky-api-docs#111]
Compare entity reference menu screen with the endpoint reference. You can see the entity reference gets out of whack and strangely organized. We should follow a similar column layout to the endpoint reference.

[Image of issue](https://files.slack.com/files-pri/T02BBN218-F4ZHFR5GX/pasted_image_at_2017_04_13_10_35_am.png)

**Comment by Blackbaud-LindseyRix** [comment]
Issue was happening because of the way the design was handling breakpoints. Fixing by converting to a yaml front matter pattern.

**Comment by Blackbaud-LindseyRix** [comment]
Fixed on test and production site. Thanks for notifying us of the issue.
