### ISSUE TITLE
Endpoint Reference column too thin

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/sky-api-docs#4]
![image](https://cloud.githubusercontent.com/assets/12037781/20270066/a44f1688-aa53-11e6-9c77-eb7a7c2ca918.png)

We have a new naming convention for endpoints that make the titles run a bit longer, which makes the reference hard to navigate. 

Can we please widen the endpoint reference navigation column?

Thank you!

**Comment by Blackbaud-LindseyRix** [comment]
This issue has been resolved with a widening of the sidebar and a hover effect for seeing the entire operation.
